development:
  network_name: Bangarang Networks
  title: Bangarang!
  ssh:
    movie_hostname: techsmix.net
    movie_dir: Movies/
    ssl_movies: https://techsmix.net/Movies/
    music_hostname: techsmix.net
    music_dir: Music/
    username: ruby
    password: gem

test:
  network_name: Bangarang Networks
  title: Bangarang!
  ssh:
    movie_hostname: techsmix.net
    movie_dir: Movies/
    music_hostname: techsmix.net
    music_dir: Music/
    username: ruby
    password: gem

production:
  network_name: Bangarang Networks
  title: Bangarang!
  ssh:
    movie_hostname: techsmix.net
    movie_dir: Movies/
    music_hostname: techsmix.net
    music_dir: Music/
    username: ruby
    password: gem
